welcome:
  - "\n§l Welcome to MonkeyCraft Creative!"
  - "\n§l Survival IP: life.monkeygamesmc.com"
  - "\n"
  - "\n§6§l>> §3§lTo start building, type or click "
  - "§b§l/plotme auto"
  - "{/plotme auto"
  - "[gives you a plot!"
  - "\n§6§l>> §3§lInfo, ranks, minigames, etc: "
  - "§b§l/faq"
  - "{/faq"
  - "[frequently asked questions and more!"
  - "\n§6§l>> §a§lDonate: "
  - "§b§l/shop"
  - "{/shop"
  - "[how you can get ranks and other goodies!"
  - "\n§6§l>> §a§lMember: "
  - "§b§l/member"
  - "{/member"
  - "[become a member!"
  - "\n§6§l>> §a§lVote for 30 minutes of WorldEdit: "
  - "§b§l/vote"
  - "{/vote"
  - "[vote to get worldedit time!"
  - "\n\n§a§l To stay updated, visit the homepage regulary!"
  - "\n§a§l Website: "
  - "§b§lwww.monkeygamesmc.com"
  - "@http://www.monkeygamesmc.com/"
  - "[stay updated!"
  - "\n"