name: MoGMCMyText-Creative
main: com.normarthehero.plugin.mytextcreative.MonkeyPlugin
version: 0.3
commands:
  join:
    description: Displays a friendly message
  shop:
    description: Links to the server store
  website:
    description: Links to the website
  faq:
    description: Links to the FAQ
  member:
    description: Links to the Member page
  sounds:
    description: Enable or Disable chat sounds
    aliases: [sound]